---
# tasks file for ./setup
- name: update all packages
  apt:
    name: "*"
    state: latest
  become: true

- name: Install dependencies 
  apt:
    pkg:
    -  libffi-dev 
    - libssl-dev 
    - python3 
    - python3-pip
  become: true 
  
- name: Remove python-configparser package
  apt:
      name: python-configparser
      state: absent
  
- name: get docker convenience script
  shell: curl -fsSL https://get.docker.com -o get-docker.sh
  args:
    creates: /home/deathstar/get-docker.sh
- name: install docker
  shell: sh /home/deathstar/get-docker.sh
  args:
    creates: /usr/bin/docker
  
- name: make deathstar user execute docker commands
  shell: usermod -aG docker deathstar

- name: install docker-compose
  shell: pip3 -v install docker-compose
  args:
      creates: /usr/local/bin/docker-compose

